spring:
  application:
    name: customer-experience-hub
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/customer_experience}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
server:
  port: 8101
